world:
  sizeMap: 800
  sizePreload: 800
  spawn:
    location: world, 0, 200, 0, 180, 0
nether:
  sizeMap: 600
  sizePreload: 600
sql:
  host: "host"
  database: "database"
  username: "username"
  password: "password"
  port: 3306
game:
  preload: true
  slot: 30
  autoStartSize: 10
  autoStartTime: 30
  hubServerName: hub