world:
  sizeMap: 800
  preload:
    enabled: true
    sizePreload: 800
  spawn:
    location: world, 0, 200, 0, 180, 0
nether:
  sizeMap: 600
  sizePreload: 600
sql:
  host: "host"
  database: "database"
  username: "user"
  password: "mdp"
  port: 3306
game:
  slot: 30
  autoStartSize: 10
  autoStartTime: 30
  hubServerName: hub