world:
  sizeMap: 800
  preload:
    enabled: true
    sizePreload: 600
  spawn:
    location: world, 0, 200, 0, 180, 0
nether:
  sizeMap: 600
  sizePreload: 600
sql:
  host: "ip"
  database: "database"
  username: "username"
  password: "password"
  port: 3306
game:
  slot: 30
  autostart: 10
  autostarttime: 30